### ISSUE TITLE
Server files v20 wont create a server

### ISSUE THREAD

**Issue by AgentCobalt8** [LunaPixelStudios/Stay-True#3]
### Describe the Bug

i followed all the directions and watched the video, the server will not start, it says there is an issue with minversion, i have the correct version of java, the eula is not being created either

### Reproduction Steps

1.download server files v20
2.follow directions to start the server
3.press run
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/98693678/151699825-858fd86f-d627-449d-9b1e-48a692bcef15.png)
![unnamed](https://user-images.githubusercontent.com/98693678/151699829-7b111936-4983-4f0a-a256-d6051089c29f.png)
![unnamed (1)](https://user-images.githubusercontent.com/98693678/151699833-d3176be7-e626-4d35-85f5-943bcac34d23.png)

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v20

### Optifine

No

### Other Mods

none

**Comment by switchnlade** [comment]
Please downgrade your java 8 version to 312 or below, you can get it from here and make sure to select the version shown in the screenshot below:
![151684065-acc81811-457a-48b5-9db9-d7488b9a3d4f](https://user-images.githubusercontent.com/96159041/151707891-1602fb25-1fab-485a-89de-53b34e42d498.png)
